### ISSUE TITLE
support for phx-feedback-for

### ISSUE THREAD

**Issue by evaldobratti** [ArthurClemens/primer_live#12]
Any way you can add support for [phx-feedback-for](https://hexdocs.pm/phoenix_live_view/form-bindings.html#phx-feedback-for) to hide error messages for inputs that were not touched yet?
I kinda made it work just by adding it [here](https://github.com/ArthurClemens/primer_live/blob/df5edf451803f6597236b67e3f01903acbb5ec20/lib/component.ex#L3084) but the input was still red, so it seems it needs more changes elsewhere.

Adding to that, when I submit a form without changing any of its inputs or when I submit it with errors, all error messages disappear, is it expected?

https://user-images.githubusercontent.com/1869525/210541896-91c6c3ab-d461-45d5-8d29-21f5e86eb919.mov

**Comment by ArthurClemens** [comment]
Working on it.

**Comment by ArthurClemens** [comment]
Fixed via #13.

Update to these versions:
- `primer_live`: `0.1.12`
- npm dependency `primer-live`: `0.1.26`
