### ISSUE TITLE
Drawer component slide-out animation issue

### ISSUE THREAD

**Issue by yasoob** [ArthurClemens/primer_live#139]
Hi! Fantastic work on this library!

I think I encountered a bug. When I open the drawers [on this page](https://primer-live.org/drawer), the initial open doesn't animate. However, every subsequent open/close is animated. It makes me think there is some issue with the initial CSS and/or JS-based state. 

Here is a short video of the bug:

https://github.com/ArthurClemens/primer_live/assets/3696393/840c23fe-22e4-4bb1-a600-219a68f85420

**Comment by ArthurClemens** [comment]
Which OS and Firefox version are you using?

**Comment by yasoob** [comment]
I tested this on Mac Ventura 13.3.1 on Chrome Version 117.0.5938.149 and Firefox version 118.0.2. Both are latest as of this message and share the same issue as in the video above.

However, surprisingly, the issue doesn't crop up on Safari on the same OS. Seems like a webkit related issue?

**Comment by yasoob** [comment]
One more datapoint. It works perfectly fine on Firefox on iOS. Only the MacOS desktop version is showing this issue.

**Comment by ArthurClemens** [comment]
I can't reproduce it, neither locally nor on BrowserStack.

**Comment by yasoob** [comment]
I will try to use an incognito tab to reproduce in a bit. Maybe some extension is interfering.

**Comment by yasoob** [comment]
Ok my apologies. I tested it in incognito window and it works without a hitch. It probably has to do with some browser plugin on my end.

**Comment by ArthurClemens** [comment]
Thanks for checking once more.
