### ISSUE TITLE
Data Tables

### ISSUE THREAD

**Issue by mitcheaton1** [ArthurClemens/primer_live#160]
Do you plan to support the Data Tables component here? I didn't see it in the Hex docs. https://primer.style/components/data-table

**Comment by ArthurClemens** [comment]
A couple of months ago, the Primer team has deprecated the Primer CSS components and to focus on React and Rails components. This has also created an influx of "new" components - in various states of completion. This to give context why a number / a lot of components are not yet included in Primer Live.

The Table component is quite elaborate, containing a number of sub components, each with its set of properties. I'll need to carve out dedicated time specifically for it. Likely not near future.

**Comment by ArthurClemens** [comment]
Note that the component is marked “experimental” at Primer Style. I’ll review it when it becomes more stable.
