### ISSUE TITLE
No card component

### ISSUE THREAD

**Issue by CharlesIrvineKC** [ArthurClemens/primer_live#177]
I just noticed that there is not card component. Are there existing components you would recommend in its place? Do you think a card component should be added? I'm just now trying things out. Please close this issue if you don't think its relevant. Thanks

**Comment by CharlesIrvineKC** [comment]
I see now. I should use the box component. I'll close this.

**Comment by ArthurClemens** [comment]
Yes, for example Blank Slate is just content inside a box: https://primer-live.org/blankslate#combined-in-a-box

**Comment by CharlesIrvineKC** [comment]
Great stuff, Arthur. I'll be using PrimerLive for the GUI's I develop for my [BPM project](https://github.com/CharlesIrvineKC/mozart). Thanks!
