### ISSUE TITLE
prompt related regression in 0.8.0

### ISSUE THREAD

**Issue by yujonglee** [ArthurClemens/primer_live#219]
I was using `0.7.0`. I followed installation guide, but I was always getting this: 
![Screenshot 2024-10-01 at 3 57 53 PM](https://github.com/user-attachments/assets/cebb1ac5-2666-4960-85bd-cf48cab6d975)

But functionality-wise, it works, so I was not paying that much attention.

But after upgrading `0.8.0`, thing like dialog stopped working with `Prompt.show is undefined.` error.

Any thoughts on this?

**Comment by ArthurClemens** [comment]
Did you see the changelog with upgrade instructions?

**Comment by yujonglee** [comment]
sorry - I should've read that first.
