### ISSUE TITLE
Toggle switch outside of form context

### ISSUE THREAD

**Issue by loop-index** [ArthurClemens/primer_live#226]
I'm trying to set up the Toggle Switch component to toggle the visibility of a view, but I'm not really sure on how to hook up the switch to an event handler. The documentation only shows how to integrate it into a form, but LiveView doesn't track form field values (I think?) so it would not rerender on toggle. I don't really want to setup a client-side hook for this, so I'm wondering if there's a straightforward way to set this up all in LiveView.

**Comment by ArthurClemens** [comment]
You can create an event using `phx-click`:
```elixir
<.toggle_switch checked={@checked} phx-click="set_toggle" phx-value={!@checked} />
```

Handle the event value:
```elixir
def handle_event("set_toggle", params, socket) do
  param_value = params["value"] || "false"

  # Update the socket based on the value...

  {:noreply, socket}
end
```

**Comment by loop-index** [comment]
That was surprisingly simple. Thank you so much!
