### ISSUE TITLE
Encountering `warning: undefined attribute "name" for component PrimerLive.Component.text_input/1`

### ISSUE THREAD

**Issue by zorn** [ArthurClemens/primer_live#51]
I'm observing a warning when attempting to assign a `name` to a `text_input` component.

<img width="799" alt="Screen Shot 2023-04-03 at 3 08 07 PM" src="https://user-images.githubusercontent.com/52168/229603902-dae96669-4a44-4a12-b9ef-866186e7b3be.png">

Looking at the component code, it is correct that there is no explicit `name` attribute. I also believe `name` is not a global attribute.

https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#module-global-attributes

To be clear, it does seem to work, and is rendered in the final output.

<img width="1003" alt="Screen Shot 2023-04-03 at 3 12 12 PM" src="https://user-images.githubusercontent.com/52168/229604604-f678580e-f20a-4b37-b439-74fa0b35c437.png">

The `name` attribute is one of the [first simple demos](https://primer-live.org/text_input#text-input) in the component preview site. Note sure what I'm doing wrong.

**Comment by ArthurClemens** [comment]
Yes, this is missing. Working on it in #52

**Comment by ArthurClemens** [comment]
Fix released in `0.2.6`.
